# Generated by Django 5.0.2 on 2024-02-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
